[Interface]
PrivateKey = qCQixCZzdFOsY73iNYgUud7kYFmesDkJlRgeAdlybFU=
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = gaWaHCurA7Pdor1OTZ6DKEXdz5tEaU+Rf2lKlnY/pUE=
# AllowedIPs = 10.8.0.0/24 — только трафик внутри VPN-сети (не ломает интернет)
# Раскомментируй 0.0.0.0/0 ТОЛЬКО если хочешь весь трафик через VPN
AllowedIPs = 10.8.0.0/24
Endpoint = 85.239.47.69:51820
PersistentKeepalive = 25
